services:
  - type: web
    name: skilltestquest-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn skilltestquest.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: skilltestquest-db
          property: connectionString

databases:
  - name: skilltestquest-db
    databaseName: skilltestquest
    user: skilltestquest_user