services:
  - type: web
    name: skilltestquest-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn skilltestquest.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: skilltestquest.settings
      - key: PYTHON_VERSION
        value: 3.11.0