# Generated by Django 6.0.2 on 2026-02-14 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='Правильный ответ')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в модуле')),
                ('task_type', models.CharField(choices=[('text', 'Текстовый ответ'), ('find_bug', 'Найди баг'), ('match', 'Сопоставление'), ('classify', 'Классификация')], default='text', max_length=50, verbose_name='Тип задания')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('attempts', models.IntegerField(default=0, verbose_name='Попыток')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
