# Generated by Django 6.0.2 on 2026-02-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('find_bug', 'Найди баг'), ('match', 'Сопоставление'), ('classify', 'Классификация'), ('multiple_choice', 'Множественный выбор')], default='text', max_length=50, verbose_name='Тип задания'),
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theories', to='tasks.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Статья теории',
                'verbose_name_plural': 'Статьи теории',
                'ordering': ['module', 'order'],
            },
        ),
    ]
